spring.application.name=membrecias-servicio
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/bd_membresia
serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# config suager

#ruta
springdoc.swagger-ui.path=/swagger-ui.html