spring.application.name=demo
server.port = 8090

# localhost:8084/pagos

spring.cloud.gateway.server.webmvc.routes[0].id=pagos
spring.cloud.gateway.server.webmvc.routes[0].uri.path=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/pagos**

spring.cloud.gateway.server.webmvc.routes[1].id=pagos
spring.cloud.gateway.server.webmvc.routes[1].uri.path=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/pagos**
